[package]
name = "hodl-chain-navio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
bls12_381.workspace = true
hmac.workspace = true
sha2.workspace = true
zeroize.workspace = true

[dev-dependencies]
hex.workspace = true
